# Generated by Django 4.2.18 on 2025-02-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image_filename',
            field=models.CharField(default='images/logo.avif', max_length=255),
        ),
    ]
