# Generated by Django 4.2.18 on 2025-02-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_workout_image_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('length', models.CharField(max_length=10)),
                ('description', models.CharField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.workout')),
            ],
        ),
    ]
