# Generated by Django 4.2.18 on 2025-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_workout_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='image_filename',
            field=models.CharField(default='images/logo.avif', max_length=255),
        ),
    ]
